### ISSUE TITLE
Сумма покупки  уходит меньше лимита

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#1]
# Описание
Если совершить покупку на сумму превышающую лимит, то должен возвращаться false
 
# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L48

# Шаги воспроизведения
1. Вставить значения переменной amount (сумма покупки) 5 001 руб
2. Вставить значения переменной creditlimit (кредитный лимит) 5 000 руб
3. Запустить программу
4. Посмотреть на вывод на консоли

*Ожидаемый результат:* Вывод на консоли результата 0 (false)

*Фактический результат:* Вывод на консоли результата - 5 001 руб

# Скриншот
![Screenshot at Nov 11 12-34-55](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/6f299da6-ca98-4741-a62d-87d3eb67c605)

# Окружение
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliJ IDEA 2023.2.2 CE
* **Java:** OPENJDK 11

**Comment by adenasky** [comment]
Исправлена логика условия баланса после покупки: 
```
        if (balance - amount > -creditLimit) {
            balance -= amount;
            return true;
```
