### ISSUE TITLE
Некорректный расчет суммы баланса в классе SavingAccount при пополнении равному установленному максимальному значению

### ISSUE THREAD

**Issue by adenasky** [Karamellnay/javaqa-team-diplom-2#10]
# Описание

При вызове метода `add`, при пополнении на сумму равную установленному максимальному значению, баланс не увеличивается на сумму пополнения.

# Локация дефекта

https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73

# Шаги воспроизведения

1. Создать объект класса SavingAccount с начальным балансом `initialBalance: 2_000`, минимальным балансом `minBalance: 1_000`, максимальным балансом `maxBalance: 10_000` и ставкой `rate: 5`.
2. Вызвать метод `add` указав сумму пополнения `amount: 8_000`.
4. Сравнить значения вывода в консоли.

*Ожидаемый результат:* баланс счета равен `10000`.
*Фактический результат:* баланс счета равен  `2000`.

# Скриншот

![Issue_addEqualsMax](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/40333167/c38cfd8e-a4e7-4461-9643-7c696b61f3ab)

# Окружение

* **Операционная система:** Windows 11 22621.2134
* **IDE:** IntelliJ IDEA 2023.2.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Karamellnay** [comment]
В метод add внесены изменения, в условие добавлено, что сумма баланса и пополнения меньше или равна максимальному балансу
if (balance + amount <= maxBalance)
