### ISSUE TITLE
Не выбрасывается исключение в конструкторе класса SavingAccount при отрицательном минимальном балансе

### ISSUE THREAD

**Issue by adenasky** [Karamellnay/javaqa-team-diplom-2#11]
# Описание

При создании объекта класса `SavingAccount` с отрицательном минимальным балансом не выбрасывается исключение `IllegalArgumentException`.

# Локация дефекта

https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать объект класса SavingAccount с начальным балансом `initialBalance: 5_000`, минимальным балансом `minBalance: -1_000`, максимальным балансом `maxBalance: 10_000` и ставкой `rate: 5`.

*Ожидаемый результат:* объект не создается, выбрасывается исключение `IllegalArgumentException`.
*Фактический результат:* объект создается, исключение `IllegalArgumentException` не выбрасывается.

# Скриншот

![Issue_exceptionLessZero](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/40333167/5a245b57-ee0d-4ec0-8141-4145dd2d21e9)

# Окружение

* **Операционная система:** Windows 11 22621.2134
* **IDE:** IntelliJ IDEA 2023.2.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Karamellnay** [comment]
Внесены изменения, добавлено исключение для отрицательного минимального баланса
if (minBalance < 0) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть отрицательным, а у вас: " + minBalance
            );
        }
