### ISSUE TITLE
Не выбрасывается исключение в конструкторе класса SavingAccount при балансе меньше минимального

### ISSUE THREAD

**Issue by adenasky** [Karamellnay/javaqa-team-diplom-2#12]
# Описание

При создании объекта класса `SavingAccount` с балансом меньше минимального установленного значения не выбрасывается исключение `IllegalArgumentException`.

# Локация дефекта

https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать объект класса SavingAccount с начальным балансом `initialBalance: 500`, минимальным балансом `minBalance: 1_000`, максимальным балансом `maxBalance: 10_000` и ставкой `rate: 5`.

*Ожидаемый результат:* объект не создается, выбрасывается исключение `IllegalArgumentException`.
*Фактический результат:* объект создается, исключение `IllegalArgumentException` не выбрасывается.

# Скриншот

![Issue_exceptionLessMin](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/40333167/aa310e7b-bc92-44a9-b827-cbfdd9cc9b23)

# Окружение

* **Операционная система:** Windows 11 22621.2134
* **IDE:** IntelliJ IDEA 2023.2.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Karamellnay** [comment]
Внесены изменения, добавлено исключение, если баланс меньше минимального баланса
if (initialBalance < minBalance) {
            throw new IllegalArgumentException(
                    "Баланс не может быть меньше минимального баланса, а у вас: " + initialBalance
            );
        }
