### ISSUE TITLE
Не выбрасывается исключение в конструкторе класса SavingAccount при балансе больше максимального

### ISSUE THREAD

**Issue by adenasky** [Karamellnay/javaqa-team-diplom-2#13]
# Описание

При создании объекта класса `SavingAccount` с балансом больше максимального установленного значения не выбрасывается исключение `IllegalArgumentException`.

# Локация дефекта

https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Создать объект класса SavingAccount с начальным балансом `initialBalance: 11_000`, минимальным балансом `minBalance: 1_000`, максимальным балансом `maxBalance: 10_000` и ставкой `rate: 5`.

*Ожидаемый результат:* объект не создается, выбрасывается исключение `IllegalArgumentException`.
*Фактический результат:* объект создается, исключение `IllegalArgumentException` не выбрасывается.

# Скриншот

![Issue_exceptionMoreMax](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/40333167/02352d45-0404-477d-bf5a-4165a94a8e4c)

# Окружение

* **Операционная система:** Windows 11 22621.2134
* **IDE:** IntelliJ IDEA 2023.2.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Karamellnay** [comment]
Внесены изменения, добавлено исключение, если баланс больше максимального баланса
if (initialBalance > maxBalance) {
            throw new IllegalArgumentException(
                    "Баланс не может быть больше максимального баланса, а у вас: " + initialBalance
            );
        }
