### ISSUE TITLE
После пополнения карты с положительным балансом сумма не увеличивается

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#2]
# Описание
Если на балансе имеются денежные средства и ее пополнить, должна возвращаться итоговая сумма баланс плюс пополнение

# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения
1. Вставить значение переменной initialBalance 1 000 руб
2. Вставить значение переменной amount 3 000 руб
3. Запустить программу
4. Посмотреть вывод на консоли

*Ожидаемый результат:* Сумма будет равна 4 000 руб
*Фактический результат:* Сумма равна 3 000 руб

# Скриншот
![Screenshot at Nov 11 12-32-45](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/b8eeb91c-c879-4504-824f-8673f65ad942)

# Окружение 
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliG IDEA 2023.2.2 CE
* **JAVA:** OPENJDK 11

**Comment by adenasky** [comment]
В переменную возвращаемого баланса добавлено условие сложения с начальным балансом:
`balance += amount;`
