### ISSUE TITLE
При покупке с положительным балансом сумма уходит в минус

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#3]
# Описание
При совершении покупку с положительным балансом, сумма покупки должна вычитаться из баланса 

# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L44

# Шаги воспроизведения
1. Вставить значения переменной amount (сумма покупки) 3 000 руб
2. Вставить значения переменной initialBalance (первоначальный баланс) 10 000 руб
3. Запустить программу
4. Посмотреть на вывод на консоли

*Ожидаемый результат:* Вывод на консоли результата - 3 000 руб 

*Фактический результат:* Вывод на консоли результата 7 000 руб

# Скриншот
![Screenshot at Nov 11 11-13-55](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/be875d96-b2cb-4a9a-ae10-4b750e719c01)

# Окружение
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliJ IDEA 2023.2.2 CE
* **Java:** OPENJDK 11

**Comment by adenasky** [comment]
В переменную возвращаемого баланса добавлено условие вычитания из начального баланса:
`balance -= amount;`
