### ISSUE TITLE
При пополнении карты с отрицательным балансом сумма не увеличивается

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#4]
# Описание
Если на балансе отрицательное значение, то после ее пополнения, должен гаситься минус по карте, оставшаяся сумма это положительный баланс 

# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения
1. Вставить значение переменной initialBalance 100 руб
2. Вставить покупку в размере 200 руб
3. Вставить значение переменной amount 300 руб
4. Запустить программу
5. Посмотреть вывод на консоли

*Ожидаемый результат:* Сумма будет равна 200 руб
*Фактический результат:* Сумма равна 300 руб

# Скриншот
![Screenshot at Nov 12 13-05-09](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/6223cdb7-cb11-484b-bc3d-739265bd68eb)

# Окружение
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliG IDEA 2023.2.2 CE
* **JAVA:** OPENJDK 11

**Comment by adenasky** [comment]
В переменную возвращаемого баланса добавлено условие сложения с начальным балансом:
`balance += amount;`
