### ISSUE TITLE
Годовые проценты не должны рассчитываться на положительный остаток по счету

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#5]
# Описание
Если на балансе положительный остаток, годовые проценты не должны рассчитываться

# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

# Шаги воспроизведения
1. Вставить значение переменной initialBalance 100 руб
2. Рассчитать годовые проценты 
3. Запустить программу
4. Посмотреть вывод на консоли

*Ожидаемый результат:* Годовые проценты равны 0 руб
*Фактический результат:* Годовые проценты равны 15 руб

# Скриншот
![Screenshot at Nov 11 11-36-50](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/c0deac27-9020-4d0f-a8df-72298bcc5bed)

# Окружение
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliG IDEA 2023.2.2 CE
* **JAVA:** OPENJDK 11

**Comment by adenasky** [comment]
Добавлено условие возврата нулевого значения при условии положительного баланса: 
```
        if (balance < 0) {
            return (balance / 100) * rate;
        } else {
            return 0;
        }
```
