### ISSUE TITLE
Начальный баланс счёта не может быть отрицательным

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#6]
# Описание
Начальный баланс счета не может быть отрицательным, должно выкидываться исключения вида IllegalArgumentException 

# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения
1. Вставить значение переменной initialBalance -100 руб
2. Запустить программу
3. Посмотреть вывод на консоли

*Ожидаемый результат:* Отрабатывает исключение вида IllegalArgumentException 
*Фактический результат:* Тест падает

# Скриншот
![Screenshot at Nov 11 11-43-06](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/57544d8a-0aa6-4f00-8cb6-c027bf5a91c6)

# Окружение
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliG IDEA 2023.2.2 CE
* **JAVA:** OPENJDK 11

**Comment by adenasky** [comment]
Добавлено исключение при отрицательном балансе:
```
        if (initialBalance < 0) { 
            throw new IllegalArgumentException(
                    "Баланс не может быть отрицательным, а у вас: " + initialBalance
            );
        }
```
