### ISSUE TITLE
Кредитный лимит не может быть отрицательным

### ISSUE THREAD

**Issue by Karamellnay** [Karamellnay/javaqa-team-diplom-2#7]
# Описание
Кредитный лимит не может быть отрицательным, должно выкидываться исключение вида IllegalArgumentException

# Локация дефекта
https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения
1. Вставить значение переменной CreditLimit -100 руб
2. Запустить программу
3. Посмотреть вывод на консоли

*Ожидаемый результат:* Отрабатывает исключение вида IllegalArgumentException
*Фактический результат:* Тест падает

# Скриншот
![Screenshot at Nov 11 11-48-47](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/144268509/f19b1950-5316-4aae-814f-0fdc89e526e2)

# Окружение
* **Операционная система:** MacOS High Sierra версия 10.13.6
* **IDE:** IntelliG IDEA 2023.2.2 CE
* **JAVA:** OPENJDK 11

**Comment by adenasky** [comment]
Добавлено исключение при отрицательном кредитном лимите:
```
        if (creditLimit < 0) {
            throw new IllegalArgumentException(
                    "Кредитный лимит не может быть отрицательным, а у вас: " + creditLimit
            );
        }
```
