### ISSUE TITLE
Выход за пределы минимального значения в классе SavingAccount при покупке больше установленного значения

### ISSUE THREAD

**Issue by adenasky** [Karamellnay/javaqa-team-diplom-2#8]
# Описание

При вызове метода `pay` баланс выходит за пределы установленного минимального значения, при покупке на сумму больше минимального значения, 

# Локация дефекта

https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L48-L49

# Шаги воспроизведения

1. Создать объект класса SavingAccount с начальным балансом `initialBalance: 2_000`, минимальным балансом `minBalance: 1_000`, максимальным балансом `maxBalance: 10_000` и ставкой `rate: 5`.
2. Вызвать метод `pay` указав сумму покупки `amount: 3_000`.
4. Сравнить значения вывода в консоли.

*Ожидаемый результат:* метод `pay` возвращает False, баланс счета не меняется.
*Фактический результат:* метод `pay` возвращает False, баланс счета равен `-1000`.

# Скриншот

![Issue_pay](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/40333167/2f04c70f-6f32-4486-a2a6-9b9e3e0bc153)

# Окружение

* **Операционная система:** Windows 11 22621.2134
* **IDE:** IntelliJ IDEA 2023.2.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Karamellnay** [comment]
В метод pay внесены изменения, в условие добавлено, что если вычитание из баланса покупки меньше  минимального баланса-возвращать false
if (balance - amount < minBalance) {
            return false;
        }
        balance -= amount;
            return true;
        }
