### ISSUE TITLE
Некорректный расчет суммы баланса в классе SavingAccount при пополнении меньше установленного максимального значения

### ISSUE THREAD

**Issue by adenasky** [Karamellnay/javaqa-team-diplom-2#9]
# Описание

При вызове метода `add` баланс не увеличивается на сумму пополнения, при пополнении на сумму меньше установленного максимального значения.

# Локация дефекта

https://github.com/Karamellnay/javaqa-team-diplom-2/blob/816b1c1732f2eb7ad123215bd9e5e7d162863d76/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73

# Шаги воспроизведения

1. Создать объект класса SavingAccount с начальным балансом `initialBalance: 2_000`, минимальным балансом `minBalance: 1_000`, максимальным балансом `maxBalance: 10_000` и ставкой `rate: 5`.
2. Вызвать метод `add` указав сумму пополнения `amount: 3_000`.
4. Сравнить значения вывода в консоли.

*Ожидаемый результат:* баланс счета равен `5000`.
*Фактический результат:* баланс счета равен  `3000`.

# Скриншот

![Issue_addLessMax](https://github.com/Karamellnay/javaqa-team-diplom-2/assets/40333167/42a793ef-21f3-41e4-86a0-baf5cf371261)

# Окружение

* **Операционная система:** Windows 11 22621.2134
* **IDE:** IntelliJ IDEA 2023.2.2 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by Karamellnay** [comment]
В метод add внесены изменения, в условие добавлено, что баланс должен увеличиться на сумму покупки 
balance += amount;
